"""Proposal Deck population for Google Slides."""

import logging
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from proposal_assistant.slides.client import SlidesClient

logger = logging.getLogger(__name__)

FOOTER_TEXT = "Draft generated by Proposal Assistant"

# Slide number → layout name (technical-design.md 4.4.3)
SLIDE_LAYOUTS: dict[int, str] = {
    1: "TITLE",
    2: "TITLE_AND_BODY",
    3: "TITLE_AND_TWO_COLUMNS",
    4: "TITLE_AND_BODY",
    5: "SECTION_TITLE_AND_DESCRIPTION",
    6: "TITLE_AND_BODY",
    7: "TITLE_AND_TWO_COLUMNS",
    8: "BIG_NUMBER",
    9: "TITLE_AND_BODY",
    10: "TITLE_AND_TWO_COLUMNS",
    11: "TITLE_AND_BODY",
    12: "TITLE_AND_BODY",
}

# Slide number → content dict key
SLIDE_CONTENT_KEYS: dict[int, str] = {
    1: "slide_1_cover",
    2: "slide_2_executive_summary",
    3: "slide_3_client_context",
    4: "slide_4_challenges",
    5: "slide_5_proposed_solution",
    6: "slide_6_solution_scope",
    7: "slide_7_implementation",
    8: "slide_8_value_case",
    9: "slide_9_commercials",
    10: "slide_10_risk_mitigation",
    11: "slide_11_proof_of_success",
    12: "slide_12_next_steps",
}

# Layout name → {content_field: (API placeholder type, placeholder index)}
# Placeholder types use Google Slides API enum values.
_PLACEHOLDER_FIELDS: dict[str, dict[str, tuple[str, int]]] = {
    "TITLE": {
        "center_title": ("CENTERED_TITLE", 0),
        "subtitle": ("SUBTITLE", 1),
    },
    "TITLE_AND_BODY": {
        "title": ("TITLE", 0),
        "body": ("BODY", 1),
    },
    "TITLE_AND_TWO_COLUMNS": {
        "title": ("TITLE", 0),
        "body_left": ("BODY", 1),
        "body_right": ("BODY", 2),
    },
    "SECTION_TITLE_AND_DESCRIPTION": {
        "title": ("TITLE", 0),
        "subtitle": ("SUBTITLE", 1),
        "body": ("BODY", 2),
    },
    "BIG_NUMBER": {
        "title": ("TITLE", 0),
        "body": ("BODY", 1),
    },
}

_GENERATED_SLIDE_COUNT = 12

# Footer positioning (EMU = English Metric Units; 1 inch = 914 400 EMU)
_EMU_PER_INCH = 914_400
_FOOTER_LEFT = int(0.34 * _EMU_PER_INCH)
_FOOTER_TOP = int(5.25 * _EMU_PER_INCH)
_FOOTER_WIDTH = int(5.0 * _EMU_PER_INCH)
_FOOTER_HEIGHT = int(0.25 * _EMU_PER_INCH)
_FOOTER_FONT_SIZE = 8  # pt


def populate_proposal_deck(
    slides: "SlidesClient",
    presentation_id: str,
    content: dict[str, Any],
) -> None:
    """Populate a Google Slides presentation with proposal content.

    Replaces placeholder text in slides 1-12 using the
    SLIDE_LAYOUTS mapping and adds a footer disclaimer to each slide.

    Args:
        slides: SlidesClient instance for API calls.
        presentation_id: Google Slides presentation ID.
        content: Proposal deck content dict with slide-keyed entries
            (slide_1_cover, slide_2_executive_summary, etc.).
            Each entry maps placeholder field names to text values.
    """
    presentation = (
        slides._slides_service.presentations()
        .get(
            presentationId=presentation_id,
            fields="slides(objectId,pageElements(" "objectId,placeholder(type,index)))",
        )
        .execute()
    )

    slide_pages = presentation.get("slides", [])
    requests: list[dict[str, Any]] = []

    for slide_num in range(1, _GENERATED_SLIDE_COUNT + 1):
        if slide_num > len(slide_pages):
            logger.warning(
                "Presentation has %d slides, expected at least %d",
                len(slide_pages),
                slide_num,
            )
            break

        slide_page = slide_pages[slide_num - 1]
        content_key = SLIDE_CONTENT_KEYS[slide_num]
        slide_content = content.get(content_key, {})
        layout_name = SLIDE_LAYOUTS[slide_num]

        _add_slide_content_requests(requests, slide_page, slide_content, layout_name)

    _add_footer_requests(requests, slide_pages)

    if requests:
        slides._slides_service.presentations().batchUpdate(
            presentationId=presentation_id,
            body={"requests": requests},
        ).execute()

    logger.info("Populated proposal deck %s", presentation_id)


# ── Slide content helpers ────────────────────────────────────────


def _add_slide_content_requests(
    requests: list[dict[str, Any]],
    slide_page: dict[str, Any],
    slide_content: dict[str, Any],
    layout_name: str,
) -> None:
    """Add text replacement requests for a single slide's placeholders."""
    field_map = _PLACEHOLDER_FIELDS.get(layout_name, {})
    shape_lookup = _build_shape_lookup(slide_page)

    for field_name, (ph_type, ph_index) in field_map.items():
        text = slide_content.get(field_name)
        if text is None:
            continue

        object_id = shape_lookup.get((ph_type, ph_index))
        if object_id is None:
            logger.warning(
                "Placeholder %s (idx %d) not found on slide %s",
                ph_type,
                ph_index,
                slide_page.get("objectId", "?"),
            )
            continue

        # Clear existing placeholder text, then insert new content
        requests.append(
            {
                "deleteText": {
                    "objectId": object_id,
                    "textRange": {"type": "ALL"},
                }
            }
        )
        requests.append(
            {
                "insertText": {
                    "objectId": object_id,
                    "text": text,
                    "insertionIndex": 0,
                }
            }
        )


def _build_shape_lookup(
    slide_page: dict[str, Any],
) -> dict[tuple[str, int], str]:
    """Build a lookup from (placeholder_type, index) to shape object ID."""
    lookup: dict[tuple[str, int], str] = {}
    for element in slide_page.get("pageElements", []):
        ph = element.get("placeholder")
        if ph:
            ph_type = ph.get("type", "")
            ph_index = ph.get("index", 0)
            lookup[(ph_type, ph_index)] = element["objectId"]
    return lookup


# ── Footer helpers ───────────────────────────────────────────────


def _add_footer_requests(
    requests: list[dict[str, Any]],
    slide_pages: list[dict[str, Any]],
) -> None:
    """Add footer text box creation requests for each slide."""
    for i, slide_page in enumerate(slide_pages):
        slide_id = slide_page.get("objectId", "")
        shape_id = f"pa_footer_{i}"

        requests.append(
            {
                "createShape": {
                    "objectId": shape_id,
                    "shapeType": "TEXT_BOX",
                    "elementProperties": {
                        "pageObjectId": slide_id,
                        "size": {
                            "width": {
                                "magnitude": _FOOTER_WIDTH,
                                "unit": "EMU",
                            },
                            "height": {
                                "magnitude": _FOOTER_HEIGHT,
                                "unit": "EMU",
                            },
                        },
                        "transform": {
                            "scaleX": 1,
                            "scaleY": 1,
                            "translateX": _FOOTER_LEFT,
                            "translateY": _FOOTER_TOP,
                            "unit": "EMU",
                        },
                    },
                }
            }
        )

        requests.append(
            {
                "insertText": {
                    "objectId": shape_id,
                    "text": FOOTER_TEXT,
                    "insertionIndex": 0,
                }
            }
        )

        requests.append(
            {
                "updateTextStyle": {
                    "objectId": shape_id,
                    "textRange": {"type": "ALL"},
                    "style": {
                        "italic": True,
                        "fontSize": {
                            "magnitude": _FOOTER_FONT_SIZE,
                            "unit": "PT",
                        },
                        "foregroundColor": {
                            "opaqueColor": {
                                "rgbColor": {
                                    "red": 0.6,
                                    "green": 0.6,
                                    "blue": 0.6,
                                }
                            }
                        },
                    },
                    "fields": "italic,fontSize,foregroundColor",
                }
            }
        )
